routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin routes
Route::group(['middleware' => 'auth'], function () {

  Route::get('/admin', 'AdminController@index');
  Route::get('/rooms', 'AdminController@rooms');
  Route::get('/report', 'AdminController@report');
  Route::get('/admin/create', 'AdminController@createUser');
  Route::get('/admin/eidt', 'AdminController@editUser');
  Route::resource('roomType', 'Admin\RoomTypeController')->except('destroy', 'show');
  Route::get('/roomType/delete/{id}', 'Admin\RoomTypeController@delete');
  Route::get('/admin/create', 'AdminController@create');
  Route::post('/admin/save', 'AdminController@save');
  Route::get('/admin/delete', 'AdminController@delete');
  Route::get('/admin/edit/{id}', 'AdminController@edit');
  Route::post('/admin/update/{id}', 'AdminController@update');
  // customer
  Route::resource('customer', 'Admin\CustomersController')->except('destroy', 'show');
  Route::get('/customer/delete/{id}', 'Admin\CustomersController@delete');
  // branch
  Route::resource('branch', 'Admin\BranchController')->except('destroy', 'show');
  Route::get('/branch/destroy/{id}', 'Admin\BranchController@destroy');
  //room
  Route::resource('room', 'Admin\RoomController')->except('destroy', 'show');
  Route::get('/room/delete/{id}', 'Admin\RoomController@delete');
  // payment
  Route::resource('payment', 'Admin\PaymentController')->except('destroy', 'show');
  Route::get('/payment/delete/{id}', 'Admin\PaymentController@delete');
  // payment type
  Route::resource('paymentType', 'Admin\PaymentTypeController');
  Route::get('/paymentType/delete/{id}', 'Admin\PaymentTypeController@delete');
});

Auth::routes();

//Front routes
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');
Route::get('/about', 'FrontController@about');
Route::get('/booking', 'FrontController@booking');
Route::get('/contact', 'FrontController@contact');
Route::get('/career', 'FrontController@career');
Route::get('/career-detail', 'FrontController@careerDetail');
Route::get('/promotion', 'FrontController@promotion');


Route::get('my-users', 'HomeController@myUsers');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'customers';

    protected $fillable = [
        'name', 'email', 'phoneNumber', 'gender', 'age'
    ];
}

app/Http/Controllers/Admin/CustomersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Customer;
use DB;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data['customers'] = DB::table('customers')->get();
        return view('admin.customers.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $customer = Customer::create([
            'name' => $request->name,
            'email' => $request->email,
            'phoneNumber' => $request->phoneNumber,
            'gender' => $request->gender,
            'age' => $request->age,
        ]);
        $i = $customer->save();
        if ($i) {
            return redirect()->route('customer.create')
                ->with('success', 'Data has been saved!');
        } else {
            return redirect()->route('customer.create')
                ->with('error', 'Fail to save data!');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $data['customer'] = Customer::find($id);
        return view('admin/customers/edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'phoneNumber' => 'required',
            'gender' => 'required',
            'age' => 'required',
        ]);

        $data = array(
            'name' => $request->name,
            'email' => $request->email,
            'phoneNumber' => $request->phoneNumber,
            'gender' => $request->gender,
            'age' => $request->age,
        );
        $i = DB::table('customers')->where('id', $id)->update($data);
        if ($i) {
            return redirect()->route('customer.edit', $id)
                ->with('success', 'Data has been saved!');
        } else {
            return redirect()->route('customer.edit', $id)
                ->with('error', 'Fail to save data!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($id)
    {
        $i = Customer::where('id', $id)->delete();
        if ($i) {
            if ($i) {
                return redirect()->route('customer.index')
                    ->with('success', 'Data has been deleted!');
            } else {
                return redirect()->route('customer.index')
                    ->with('error', 'Fail to delete data!');
            }
        }
    }
}

resources/views/admin/customers/create.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Create Customer</h1>
    <form action="{{route('customer.store')}}" method="POST">
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{url('customer')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          <div>
            {{csrf_field()}}
            <div class="form-group row">
              <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter your Name" value="{{old('name')}}" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Email <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="email" class="form-control" id="email" name="email" value="{{old('email')}}" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Phone Number <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="phoneNumber" name="phoneNumber" value="{{old('phoneNumber')}}" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Gender <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                    <select class="form-control" value="" name="gender" id="gender">
                        <option id="gender" value="">Select</option>
                        <option id="gender" value="male" name="male">Male</option>
                        <option id="gender" value="female" name="female">Female</option>
                     </select>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Age <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="number" class="form-control" id="age" name="age" value="{{old('age')}}" required autofocus>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

resources/views/admin/customers/edit.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Edit Customer</h1>
    <form action="{{route('customer.update', $customer->id)}}" method="POST">
      {{ method_field('PUT') }}
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{url('customer')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          <div>
            {{csrf_field()}}
            <div class="form-group row">
              <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter your Name" value="{{$customer->name}}" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Email <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="email" class="form-control" id="email" name="email" value="{{$customer->email}}" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Phone Number <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="phoneNumber" name="phoneNumber" value="{{$customer->phoneNumber}}" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Gender <span class="text-danger">*</span></label>
                <div class="col-sm-8">
                    <select class="form-control" value="{{$customer->gender}}" name="gender" id="gender">
                        <option id="gender" value="{{$customer->gender}}">{{$customer->gender}}</option>
                        <option id="gender" value="male" name="male">Male</option>
                        <option id="gender" value="female" name="female">Female</option>
                    </select>
              </div>
            </div>
            <div class="form-group row">
              <label for="Type" class="col-sm-4 form-control-label">Age <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="number" class="form-control" id="age" name="age" value="{{$customer->age}}" required autofocus>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

resources/views/admin/customers/index.blade.php
@extends('layouts.admin')
@section('style')
<style>
   .users__btn__add {
   margin-bottom: 30px;
   }
   .users__table {
   width:100%;
   }
   .item__action {
   width: 140px;
   }
   .item__action__btn {
   display:flex;
   justify-content:space-between;
   }
   .form__btn {
      display: flex;
      justify-content: space-between;
   }
</style>
@endsection
@section('content')
<section class="section">
   <div class="create">
      <div class="row" style="margin-bottom: 20px;">
         <div class="col-md-6">
            <h1>Customers</h1>
         </div>
         <div class="col-md-6" style="text-align: right;">
            <a href="{{url('customer/create')}}" class="btn btn-primary btn-sm" title="Create">
               <i class="fa fa-plus"></i> Create
            </a>
         </div>
      </div>
   <div class="customer">
      <div>
         <table id="example" class="table table-striped table-bordered users__table">
            <thead>
               <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone Number</th>
                  <th>Gender</th>
                  <th>Age</th>
                  <th>Action</th>
               </tr>
            </thead>
            <tbody>
               @php($i=1)
               @foreach ($customers as $c)
               <tr>
                  <td>{{$i++}}</td>
                  <td>{{$c->name}}</td>
                  <td>{{$c->email}}</td>
                  <td>{{$c->phoneNumber}}</td>
                  <td>{{$c->gender}}</td>
                  <td>{{$c->age}}</td>
                  <td>
                     <a href="{{url('customer/delete', $c->id)}}" class="text-danger" title="Delete"
                        onclick="return confirm('Are you sure to delete?')">
                     <i class="fa fa-trash"></i>
                     </a>
                     &nbsp;&nbsp;
                     <a href="{{route('customer.edit', $c->id)}}" class="text-success">
                     <i class="fa fa-edit"></i>
                     </a>
                  </td>
               </tr>
               @endforeach
            </tbody>
         </table>
      </div>
   </div>
</section>
@stop