routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin routes
Route::group(['middleware' => 'auth'], function () {

  Route::get('/admin', 'AdminController@index');
  Route::get('/rooms', 'AdminController@rooms');
  Route::get('/report', 'AdminController@report');
  Route::get('/admin/create', 'AdminController@createUser');
  Route::get('/admin/eidt', 'AdminController@editUser');
  Route::resource('roomType', 'Admin\RoomTypeController')->except('destroy', 'show');
  Route::get('/roomType/delete/{id}', 'Admin\RoomTypeController@delete');
  Route::get('/admin/create', 'AdminController@create');
  Route::post('/admin/save', 'AdminController@save');
  Route::get('/admin/delete', 'AdminController@delete');
  Route::get('/admin/edit/{id}', 'AdminController@edit');
  Route::post('/admin/update/{id}', 'AdminController@update');
  // customer
  Route::resource('customer', 'Admin\CustomersController')->except('destroy', 'show');
  Route::get('/customer/delete/{id}', 'Admin\CustomersController@delete');
  // branch
  Route::resource('branch', 'Admin\BranchController')->except('destroy', 'show');
  Route::get('/branch/destroy/{id}', 'Admin\BranchController@destroy');
  //room
  Route::resource('room', 'Admin\RoomController')->except('destroy', 'show');
  Route::get('/room/delete/{id}', 'Admin\RoomController@delete');
  // payment
  Route::resource('payment', 'Admin\PaymentController')->except('destroy', 'show');
  Route::get('/payment/delete/{id}', 'Admin\PaymentController@delete');
  // payment type
  Route::resource('paymentType', 'Admin\PaymentTypeController');
  Route::get('/paymentType/delete/{id}', 'Admin\PaymentTypeController@delete');
});

Auth::routes();

//Front routes
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');
Route::get('/about', 'FrontController@about');
Route::get('/booking', 'FrontController@booking');
Route::get('/contact', 'FrontController@contact');
Route::get('/career', 'FrontController@career');
Route::get('/career-detail', 'FrontController@careerDetail');
Route::get('/promotion', 'FrontController@promotion');


Route::get('my-users', 'HomeController@myUsers');

app/Http/Controllers/Admin/RoomTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\RoomType;
use DB;

class RoomTypeController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
   */
  public function index()
  {
    $data['roomTypes'] = RoomType::all();
    return view('admin/room-type/index', $data);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
   */
  public function create()
  {
    return view('admin/room-type/create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\RedirectResponse
   */
  public function store(Request $request)
  {
    $roomType = RoomType::create([
      'name' => $request->name,
      'description' => $request->description,
    ]);
    $i = $roomType->save();
    if ($i) {
      return redirect()->route('roomType.create')
        ->with('success', 'Data has been saved!');
    } else {
      return redirect()->route('roomType.create')
        ->with('error', 'Fail to save data!');
    }
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
   */
  public function edit($id)
  {
    $data['roomType'] = RoomType::find($id);
    return view('admin/room-type/edit', $data);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\RedirectResponse
   */
  public function update(Request $request, $id)
  {
    $request->validate([
      'name' => 'required',
      'description' => 'required',
    ]);
    $data = array(
      'name' => $request->name,
      'description' => $request->description,
    );
    $i = DB::table('room_types')->where('id', $id)->update($data);
    if ($i) {
      return redirect()->route('roomType.edit', $id)
        ->with('success', 'Data has been saved!');
    } else {
      return redirect()->route('roomType.edit', $id)
        ->with('error', 'Fail to save data!');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\RedirectResponse
   */
  public function delete($id)
  {
    $i = RoomType::where('id', $id)->delete();
    if ($i) {
      if ($i) {
        return redirect()->route('roomType.index')
          ->with('success', 'Data has been deleted!');
      } else {
        return redirect()->route('roomType.index')
          ->with('error', 'Fail to delete data!');
      }
    }
  }
}

resources/views/admin/room-type/create.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Create Room Type</h1>
    <form action="{{route('roomType.store')}}" method="POST">
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{route('roomType.index')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          {{csrf_field()}}
          <div class="form-group row">
            <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{old('name')}}" required autofocus>
            </div>
          </div>
          <div class="form-group row">
            <label for="description" class="col-sm-4 form-control-label">Description <span class="text-danger">*</span></label>
            <div class="col-sm-8">
                <textarea class="form-control rounded-0" id="description" name="description" rows="5" value="{{old('description')}}"></textarea>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

@section('js')
<script>
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection

resources/views/admin/room-type/edit.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Edit Room Type</h1>
    <form action="{{route('roomType.update', $roomType->id)}}" method="POST">
      {{ method_field('PUT') }}
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{route('roomType.index')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          {{csrf_field()}}
          <div class="form-group row">
            <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{$roomType->name}}" required autofocus>
            </div>
          </div>
          <div class="form-group row">
            <label for="description" class="col-sm-4 form-control-label">Description <span class="text-danger">*</span></label>
            <div class="col-sm-8">
                <textarea class="form-control rounded-0" id="description" name="description" rows="5" >{{$roomType->description}}</textarea>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

@section('js')
<script>
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection

resources/views/admin/room-type/index.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-6">
        <h1>Room Type</h1>
      </div>
      <div class="col-md-6" style="text-align: right;">
        <a href="{{route('roomType.create')}}" class="btn btn-primary btn-sm" title="Create">
          <i class="fa fa-plus"></i> Create
        </a>
      </div>
    </div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Description</th>
          <th>Created Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php $i = 1; ?>
        @foreach($roomTypes as $roomType)
        <tr>
          <td>{{$i++}}</td>
          <td>{{$roomType->name}}</td>
          <td>{{$roomType->description}}</td>
          <td>{{$roomType->created_at}}</td>
          <td class="action">
            <a href="{{url('roomType/delete', $roomType->id)}}" title="Delete" class='text-danger' onclick="return confirm('You want to delete?')">
              <i class="fa fa-trash"></i>
            </a>&nbsp;
            <a href="{{route('roomType.edit', $roomType->id)}}" class="text-success" title="Edit">
              <i class="fa fa-edit"></i>
            </a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
</section>
@endsection

@section('js')
<script>
  $(document).ready(function() {
    $('#example').DataTable();
  });
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection