routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin routes
Route::group(['middleware' => 'auth'], function () {

  Route::get('/admin', 'AdminController@index');
  Route::get('/rooms', 'AdminController@rooms');
  Route::get('/report', 'AdminController@report');
  Route::get('/admin/create', 'AdminController@createUser');
  Route::get('/admin/eidt', 'AdminController@editUser');
  Route::resource('roomType', 'Admin\RoomTypeController')->except('destroy', 'show');
  Route::get('/roomType/delete/{id}', 'Admin\RoomTypeController@delete');
  Route::get('/admin/create', 'AdminController@create');
  Route::post('/admin/save', 'AdminController@save');
  Route::get('/admin/delete', 'AdminController@delete');
  Route::get('/admin/edit/{id}', 'AdminController@edit');
  Route::post('/admin/update/{id}', 'AdminController@update');
  // customer
  Route::resource('customer', 'Admin\CustomersController')->except('destroy', 'show');
  Route::get('/customer/delete/{id}', 'Admin\CustomersController@delete');
  // branch
  Route::resource('branch', 'Admin\BranchController')->except('destroy', 'show');
  Route::get('/branch/destroy/{id}', 'Admin\BranchController@destroy');
  //room
  Route::resource('room', 'Admin\RoomController')->except('destroy', 'show');
  Route::get('/room/delete/{id}', 'Admin\RoomController@delete');
  // payment
  Route::resource('payment', 'Admin\PaymentController')->except('destroy', 'show');
  Route::get('/payment/delete/{id}', 'Admin\PaymentController@delete');
  // payment type
  Route::resource('paymentType', 'Admin\PaymentTypeController');
  Route::get('/paymentType/delete/{id}', 'Admin\PaymentTypeController@delete');
});

Auth::routes();

//Front routes
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');
Route::get('/about', 'FrontController@about');
Route::get('/booking', 'FrontController@booking');
Route::get('/contact', 'FrontController@contact');
Route::get('/career', 'FrontController@career');
Route::get('/career-detail', 'FrontController@careerDetail');
Route::get('/promotion', 'FrontController@promotion');


Route::get('my-users', 'HomeController@myUsers');

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $fillable = [
        'roomNo', 'roomTypeId', 'rate', 'price', 'branchId', 'adult', 'child',
    ];
}

app/Models/RoomType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RoomType extends Model
{
    /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
    protected $fillable = [
      'name', 'description',
    ];

}

app/Http/Controllers/Admin/RoomController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Room;
use App\Models\RoomType;
use DB;

class RoomController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
   */
  public function index()
  {
    $data['rooms'] = DB::table('rooms')
      ->join('room_types', 'rooms.roomTypeId', '=', 'room_types.id')
      ->join('branches', 'rooms.branchId', '=', 'branches.id')
      ->select('rooms.*', 'room_types.name as roomType', 'branches.branchName as branch')
      ->get();
    return view('admin/room/index', $data);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
   */
  public function create()
  {
    $data['roomTypes'] = RoomType::all();
    $data['branches'] = DB::table('branches')->get();
    return view('admin/room/create', $data);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\RedirectResponse
   */
  public function store(Request $request)
  {
    $room = Room::create([
      'roomNo' => $request->roomNo,
      'roomTypeId' => $request->roomTypeId,
      'rate' => $request->rate,
      'price' => $request->price,
      'branchId' => $request->branchId,
      'adult' => $request->adult,
      'child' => $request->child,
    ]);
    $i = $room->save();
    if ($i) {
      return redirect()->route('room.create')
        ->with('success', 'Data has been saved!');
    } else {
      return redirect()->route('room.create')
        ->with('error', 'Fail to save data!');
    }
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
   */
  public function edit($id)
  {
    $data['room'] = Room::find($id);
    $data['roomTypes'] = RoomType::all();
    $data['branches'] = DB::table('branches')->get();
    return view('admin/room/edit', $data);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\RedirectResponse
   */
  public function update(Request $request, $id)
  {
    $request->validate([
      'roomNo' => 'required',
      'roomTypeId' => 'required',
      'price' => 'required',
      'branchId' => 'required',
      'adult' => 'required',
      'child' => 'required',
    ]);

    $data = array(
      'roomNo' => $request->roomNo,
      'roomTypeId' => $request->roomTypeId,
      'rate' => $request->rate,
      'price' => $request->price,
      'branchId' => $request->branchId,
      'adult' => $request->adult,
      'child' => $request->child,
    );
    $i = DB::table('rooms')->where('id', $id)->update($data);
    if ($i) {
      return redirect()->route('room.edit', $id)
        ->with('success', 'Data has been saved!');
    } else {
      return redirect()->route('room.edit', $id)
        ->with('error', 'Fail to save data!');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\RedirectResponse
   */
  public function delete($id)
  {
    $i = Room::where('id', $id)->delete();
    if ($i) {
      if ($i) {
        return redirect()->route('room.index')
          ->with('success', 'Data has been deleted!');
      } else {
        return redirect()->route('room.index')
          ->with('error', 'Fail to delete data!');
      }
    }
  }
}

resources/views/admin/room/create.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Create Room</h1>
    <form action="{{route('room.store')}}" method="POST">
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{route('room.index')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          {{csrf_field()}}
          <div class="form-group row">
            <label for="roomNo" class="col-sm-4 form-control-label">Room No <span class="text-danger">*</span></label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="roomNo" name="roomNo" placeholder="room number" value="{{old('roomNo')}}" required autofocus>
            </div>
          </div>
          <div class="form-group row">
            <label for="roomTypeId" class="col-sm-4 form-control-label">Room Type</label>
            <div class="col-sm-8">
              <select class="form-control" name="roomTypeId" id="roomTypeId">
                @foreach($roomTypes as $roomType)
                <option value="{{$roomType->id}}">{{$roomType->name}}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="rate" class="col-sm-4 form-control-label">Rate</label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="rate" name="rate" placeholder="Rate" value="{{old('rate')}}">
            </div>
          </div>
          <div class="form-group row">
            <label for="price" class="col-sm-4 form-control-label">Price <span class="text-danger">*</span></label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="price" name="price" placeholder="Price" value="{{old('roomNo')}}" required autofocus>
            </div>
          </div>
          <div class="form-group row">
            <label for="branchId" class="col-sm-4 form-control-label">Branch</label>
            <div class="col-sm-8">
              <select class="form-control" name="branchId" id="branchId">
                <option value="">select branch</option>
                @foreach($branches as $branch)
                <option value="{{$branch->id}}">{{$branch->branchName}}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="adult" class="col-sm-4 form-control-label">Adult</label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="adult" name="adult" placeholder="Adult" value="{{old('adult')}}">
            </div>
          </div>
          <div class="form-group row">
            <label for="child" class="col-sm-4 form-control-label">Child</label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="child" name="child" placeholder="Child" value="{{old('child')}}">
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

@section('js')
<script>
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection

resources/views/admin/room/edit.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Create Room</h1>
    <form action="{{route('room.update',  $room->id)}}" method="POST">
      {{ method_field('PUT') }}
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{route('room.index')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          {{csrf_field()}}
          <div class="form-group row">
            <label for="roomNo" class="col-sm-4 form-control-label">Room No <span class="text-danger">*</span></label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="roomNo" name="roomNo" placeholder="room number" value="{{$room->roomNo}}" required autofocus>
            </div>
          </div>
          <div class="form-group row">
            <label for="roomTypeId" class="col-sm-4 form-control-label">Room Type</label>
            <div class="col-sm-8">
              <select class="form-control" name="roomTypeId" id="roomTypeId">
                <option value=""></option>
                @foreach($roomTypes as $roomType)
                <option value="{{$roomType->id}}" {{$room->roomTypeId==$roomType->id?'selected':''}}>{{$roomType->name}}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="rate" class="col-sm-4 form-control-label">Rate</label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="rate" name="rate" placeholder="Rate" value="{{$room->rate}}">
            </div>
          </div>
          <div class="form-group row">
            <label for="price" class="col-sm-4 form-control-label">Price <span class="text-danger">*</span></label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="price" name="price" placeholder="Price" value="{{$room->price}}" required autofocus>
            </div>
          </div>
          <div class="form-group row">
            <label for="branchId" class="col-sm-4 form-control-label">Branch</label>
            <div class="col-sm-8">
              <select class="form-control" name="branchId" id="branchId">
                <option value=""></option>
                @foreach($branches as $branch)
                <option value="{{$branch->id}}" {{$room->branchId==$branch->id?'selected':''}}>{{$branch->branchName}}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="adult" class="col-sm-4 form-control-label">Adult</label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="adult" name="adult" placeholder="Adult" value="{{$room->adult}}">
            </div>
          </div>
          <div class="form-group row">
            <label for="child" class="col-sm-4 form-control-label">Child</label>
            <div class="col-sm-8">
              <input type="number" class="form-control" id="child" name="child" placeholder="Child" value="{{$room->child}}">
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

@section('js')
<script>
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection

resources/views/admin/room/index.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-6">
        <h1>Room</h1>
      </div>
      <div class="col-md-6" style="text-align: right;">
        <a href="{{route('room.create')}}" class="btn btn-primary btn-sm" title="Create">
          <i class="fa fa-plus"></i> Create
        </a>
      </div>
    </div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Id</th>
          <th>Room No</th>
          <th>Room Type</th>
          <th>Rate</th>
          <th>Price</th>
          <th>Branch</th>
          <th>Adult</th>
          <th>Child</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php $i = 1; ?>
        @foreach($rooms as $room)
        <tr>
          <td>{{$i++}}</td>
          <td>{{$room->roomNo}}</td>
          <td>{{$room->roomType}}</td>
          <td>{{$room->rate}}</td>
          <td>{{$room->price}}</td>
          <td>{{$room->branch}}</td>
          <td>{{$room->adult}}</td>
          <td>{{$room->child}}</td>
          <td class="action">
            <a href="{{url('room/delete', $room->id)}}" title="Delete" class='text-danger' onclick="return confirm('You want to delete?')">
              <i class="fa fa-trash"></i>
            </a>&nbsp;
            <a href="{{route('room.edit', $room->id)}}" class="text-success" title="Edit">
              <i class="fa fa-edit"></i>
            </a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
</section>
@endsection

@section('js')
<script>
  $(document).ready(function() {
    $('#example').DataTable();
  });
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection