routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin routes
Route::group(['middleware' => 'auth'], function () {

  Route::get('/admin', 'AdminController@index');
  Route::get('/rooms', 'AdminController@rooms');
  Route::get('/report', 'AdminController@report');
  Route::get('/admin/create', 'AdminController@createUser');
  Route::get('/admin/eidt', 'AdminController@editUser');
  Route::resource('roomType', 'Admin\RoomTypeController')->except('destroy', 'show');
  Route::get('/roomType/delete/{id}', 'Admin\RoomTypeController@delete');
  Route::get('/admin/create', 'AdminController@create');
  Route::post('/admin/save', 'AdminController@save');
  Route::get('/admin/delete', 'AdminController@delete');
  Route::get('/admin/edit/{id}', 'AdminController@edit');
  Route::post('/admin/update/{id}', 'AdminController@update');
  // customer
  Route::resource('customer', 'Admin\CustomersController')->except('destroy', 'show');
  Route::get('/customer/delete/{id}', 'Admin\CustomersController@delete');
  // branch
  Route::resource('branch', 'Admin\BranchController')->except('destroy', 'show');
  Route::get('/branch/destroy/{id}', 'Admin\BranchController@destroy');
  //room
  Route::resource('room', 'Admin\RoomController')->except('destroy', 'show');
  Route::get('/room/delete/{id}', 'Admin\RoomController@delete');
  // payment
  Route::resource('payment', 'Admin\PaymentController')->except('destroy', 'show');
  Route::get('/payment/delete/{id}', 'Admin\PaymentController@delete');
  // payment type
  Route::resource('paymentType', 'Admin\PaymentTypeController');
  Route::get('/paymentType/delete/{id}', 'Admin\PaymentTypeController@delete');
});

Auth::routes();

//Front routes
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');
Route::get('/about', 'FrontController@about');
Route::get('/booking', 'FrontController@booking');
Route::get('/contact', 'FrontController@contact');
Route::get('/career', 'FrontController@career');
Route::get('/career-detail', 'FrontController@careerDetail');
Route::get('/promotion', 'FrontController@promotion');


Route::get('my-users', 'HomeController@myUsers');

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- Bootstrap CSS CDN -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
   <!-- Our Custom CSS -->
   <link rel="stylesheet" href="{{ URL::asset('css/admin.css')}}">
   <!-- Font Awesome JS -->
   <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
   <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
   </link>
   <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   </link>
   <style>
      .wrapper {
         display: flex;
         align-items: stretch;
      }

      #sidebar {
         min-width: 250px;
         max-width: 250px;
         min-height: 120vh;
      }

      #sidebar.active {
         margin-left: -250px;
      }

      a[data-toggle="collapse"] {
         position: relative;
      }

      .dropdown-toggle::after {
         display: block;
         position: absolute;
         top: 50%;
         right: 20px;
         transform: translateY(-50%);
      }

      @media (max-width: 768px) {
         #sidebar {
            margin-left: -250px;
         }

         #sidebar.active {
            margin-left: 0;
         }
      }

      @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";

      body {
         font-family: 'Poppins', sans-serif;
         background: #fafafa;
      }

      p {
         font-family: 'Poppins', sans-serif;
         line-height: 1.7em;
         color: #999;
      }

      a,
      a:hover,
      a:focus {
         color: inherit;
         text-decoration: none;
         transition: all 0.3s;
      }

      #sidebar {
         /* don't forget to add all the previously mentioned styles here too */
         background: #202429;
         color: #fff;
         transition: all 0.3s;
      }

      #sidebar .sidebar-header {
         padding: 20px;
         background: #1cc3b2;
      }

      #sidebar ul.components {
         padding: 20px 0;
         border-bottom: 1px solid #47748b;
      }

      #sidebar ul p {
         color: #fff;
         padding: 10px;
      }

      #sidebar ul li a {
         padding: 10px 30px;
         font-size: 14px;
         display: block;
      }

      #sidebar ul li a:hover {
         color: white;
         background: #474545;
      }

      #sidebar ul li.active>a,
      a[aria-expanded="true"] {
         color: #fff;
         background: #474545;
      }

      .content {
         width: 90%;
         margin: 2% 5%;
      }

      .sidebar__title {
         text-align: center;
      }
   </style>
   @yield('style')
</head>

<body>
   <div style="display: flex;">
      <div id="wrapper">
         <!-- Sidebar -->
         <nav id="sidebar">
            <div class="sidemenu">
               <ul class="list-unstyled components">
                  <div style="text-align:center">
                     <a class="navbar-brand" href="{{ url('admin') }}">
                        <i class="fa fa-h-square text-brand fa-3x"></i><strong class="text-brand" style="font-size: 34px;">otel</strong>
                     </a>
                  </div>
                  <hr>
                  <li class="active">
                     <a href="/admin"><i class="fa fa-user-friends"></i> &nbsp; Users</a>
                  </li>
                  <li>
                     <a href="/customer"><i class="fa fa-users"></i> &nbsp; Customers</a>
                  </li>
                  <li>
                     <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-home"></i> &nbsp; Room</a>
                     <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                           <a href="{{route('room.index') }}">Room</a>
                           <a href="{{route('roomType.index') }}">Room Type</a>
                        </li>
                     </ul>
                  </li>
                  <li>
                     <a href="#payment" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-dollar-sign"></i> &nbsp; Payment</a>
                     <ul class="collapse list-unstyled" id="payment">
                        <li>
                           <a href="{{url('/payment') }}">Payment</a>
                        </li>
                        <li>
                           <a href="{{url('/paymentType') }}">Payment Type</a>
                        </li>
                     </ul>
                  </li>
                  <li>
                     <a href="/branch"> <i class="fa fa-location-arrow"></i> &nbsp;Branch</a>
                  </li>
                  <li>
                     <a href="#"><i class="fa fa-address-card"></i> &nbsp;Contact</a>
                  </li>
               </ul>
            </div>
         </nav>
      </div>
      <div class=" main" style="width: 100%;">
         <div class="content">
            <!-- content  -->
            @yield('content')
         </div>
      </div>

      <!-- /#page-wrapper -->
      <!-- jQuery CDN - Slim version (=without AJAX) -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <!-- Popper.JS -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
      <!-- Bootstrap JS -->
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
      <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
      <script>
         $(document).ready(function() {

            $('#sidebarCollapse').on('click', function() {
               $('#sidebar').toggleClass('active');
            });
            //Set active menu
            var url = window.location.href;
            $(".sidemenu a").each(function() {
               // checks if its the same on the address bar
               if (url == (this.href)) {
                  $('li').removeClass('active');
                  $(this).closest("li").addClass("active");
               }
            });

         });

         $(document).ready(function() {
            $('#example').DataTable();
         });
      </script>
      @yield('js')
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Hotel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Hotel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Hotel | Login</title>
  <!-- CSRF Token -->
  <title>{{ config('app.name', 'Hotel') }}</title>
  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  <!-- Styles -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    body {background: #1cc3b2;}
    .btn-cancel {color: white;}
    .btn-cancel:hover {
      color: white;
      text-decoration: none
    }

    .invalid-feedback {
      font-size: 11px;
      color: red;
    }

    .text-white {
      color: white
    }

    .justify-content-center {
      margin-top: 100px;
    }

    .con-form {
      background: white;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
  </style>
</head>

<body>
  <div class="container" id="main-container">
    <div class="row justify-content-center">
      @yield('content')
    </div>
  </div>
</body>

</html>

resources/views/layouts/front.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Hotel | Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{{ url('storage/images/main/orkide.png') }}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Battambang|Koulen&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+SC&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ URL::asset('css/front.css')}}">

  <style>
    .banner-section {
      background-image: url('{{ url("storage/images/banner_home.jpg") }}');
      background-repeat: no-repeat;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      height: auto;
    }

    .banner-section {
      margin-right: 0;
    }

    .col-md-1 {
      width: 4.333333%;
    }
  </style>
  @yield('style')

</head>

<body class="background-body-image">

  {{--Menu Section--}}
  <nav class="navbar navbar-default navbar-fixed-top clear-padding" style="border: none; background: none;">
    <div class="container-fluid middle-header">
      <div class="container" style="padding: 5px;">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url('home') }}">
            <i class="fa fa-h-square text-brand fa-3x"></i><strong class="text-brand" style="font-size: 34px;">otel</strong>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu" id="bs-example-navbar-collapse-1" style="margin-top: 6px;">
          <ul class="nav navbar-nav navbar-right">
            <li class="active link"><a href="{{ url('home') }}" class="header-nav-link">@lang("HOME")</a></li>
            <li class="link"><a href="{{ url('about') }}" class="header-nav-link">@lang("ABOUT US")</a></li>
            <li class="link"><a href="{{ url('booking') }}" class="header-nav-link">@lang("BOOKING")</a></li>
            <li class="link"><a href="{{ url('promotion') }}" class="header-nav-link">@lang("SPECIAL OFFER")</a></li>
            <li class="link"><a href="{{ url('contact') }}" class="header-nav-link">@lang("CONTACT US")</a></li>
            <li class="link"><a href="{{ url('career') }}" class="header-nav-link">@lang("CAREER")</a></li>
            @guest
            <li class="link"><a class="header-nav-link" href="{{ route('login') }}"><i class="fa fa-sign-in"></i> {{ __('Login') }}</a></li>
            @endguest
            @auth
            <li><a class="header-nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                <i class="fa fa-sign-out pull-right"></i> LogOut</a>
            </li>
            <li class="pull-right"><a class="header-nav-link" href="{{ url('admin') }}"><i class="fa fa-tachometer text-brand"></i></a></li>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              {{ csrf_field() }}
            </form>
            @endauth
          </ul>
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  {{--End Menu Section--}}

  {{-- banner --}}
  <div class="conterin-fluid clear-padding" id="banner">
    <div class="banner-section row">
      @yield('banner')
    </div>
  </div>
  {{-- End banner --}}

  {{--body--}}
  <div class="container-fluid clear-padding" id="main-container" style="margin:20px 0 20px  0px">

    @yield('content')

  </div>
  {{--end body--}}
  {{--Footer--}}
  <div class="container-fluid">
    <div class="row section-map">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3909.0527841172734!2d104.91711721548545!3d11.548071391800725!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x310951216e7aaaab%3A0xbc67a2b632a5446!2sSokha%20Hotel%20Phnom%20Penh!5e0!3m2!1sen!2skh!4v1594888453696!5m2!1sen!2skh" width="100%" height="380" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <div class="row footer-bottom">
      <br>
      <div class="container">
        <div class="row">
          <ul class="footer-end">
            <a href="#">
              <li><strong>© Hotel 2008 - 2020</strong></li>
            </a>
            <a href="#">
              <li>Terms and Conditions</li>
            </a>
            <a href="#">
              <li>Privacy Policy</li>
            </a>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {{--End Footer--}}

  <script>
    var bannerHeight = $('#banner').height();
    (function($) {
      $('.dropdown-submenu a.submenu').on("click", function(e) {
        $(this).next('ul').toggle();
        e.stopPropagation();
        e.preventDefault();
      });

      //Set active menu
      var url = window.location.href;
      // passes on every "a" tag
      $(".menu a").each(function() {
        // checks if its the same on the address bar
        if (url == (this.href)) {
          $('li').removeClass('active');
          $(this).closest("li").addClass("active");
        }
      });

      function setDefaultMenu() {
        $(".middle-header").css({
          "background-color": "rgba(0, 0, 0, 0.5)"
        });
        $(".navbar-default .navbar-nav>li>a").css("color", "white");
      }

      function changeMenu() {
        $(".middle-header").css({
          "background-color": "white"
        });
        $(".navbar-default .navbar-nav>li>a").css("color", "#1cc3b2");
      }

      $(window).scroll(function(event) {
        event.preventDefault();
        var scroll = $(window).scrollTop();

        //bigger than 1000: show middle header, change navbar color background
        if (scroll > bannerHeight) {
          changeMenu();
        } else {
          setDefaultMenu();
        }
      });
    })(jQuery);

    $(function() {
      function scrollToAnchor(aid) {
        $('html,body').animate({
          scrollTop: $(aid).offset().top - 52
        }, 'slow');
      }
      $(".link-inside-menu").click(function(e) {
        e.preventDefault();
        scrollToAnchor($(this).attr("href"));
      });
    })
  </script>

  @yield('js')

</body>

</html>